-- ─────────────────────────────────────────────────────────────────────────
-- DEPRECATED — superseded before reaching production-stable.
-- ─────────────────────────────────────────────────────────────────────────
--
-- An earlier draft of this migration created parallel data_filter +
-- filter_access tables for the views→filters cutover. We then realised
-- the filter model is purely a UI rename of the view model: same data,
-- same access workflow, only different routes. Cleaner to point the
-- /filters routes at the existing data_view + view_access tables and
-- skip the duplication entirely.
--
-- The first deploy of this file did create empty data_filter +
-- filter_access tables (and copied rows into them). Those are dormant
-- and unused — left in place for a release in case rollback is needed.
-- A follow-up cleanup migration can drop them after PR3 lands.
--
-- This is intentionally a no-op now (re-running is safe).
SELECT 1;
